blorgh/config/routes.rb
require 'subscribem/constraints/subdomain_required'


Blorgh::Application.routes.draw do

  constraints(Subscribem::Constraints::SubdomainRequired) do


    root :to => "posts#index"
    resources :posts, only: [:index, :show] do
      resources :comments
    end

    namespace :api do
      resources :posts do
        resources :comments
      end
    end

    namespace :admin do
      resources :posts
    end

  end

  mount Subscribem::Engine, at: '/'
end

blorgh/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

blorgh/app/models/post.rb
class Post < ActiveRecord::Base
  extend Subscribem::ScopedTo
  has_many :comments
end

blorgh/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

blorgh/app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  before_action :set_post

  def index
    @comments = @post.comments
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

blorgh/app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      render :show, :status => 201
    else
      render "api/shared/errors", resource: @post, status: 422
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      render :show
    else
      render "api/shared/errors", resource: @post, status: 422
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    render nothing: true
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

blorgh/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery# with: :exception

#  def current_user
#    env['warden'].user
#  end
#  helper_method :current_user

#  def signed_in?
#    env['warden'].authenticated?
#  end
#  helper_method :signed_in?

  def admin?
    current_user && current_account.owner == current_user
  end
  helper_method :admin?
end

blorgh/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.new(comment_params)
    if @comment.save
      redirect_to @post
    else
      render action: 'new'
    end
  end

  private
    def set_post
      @post = Post.find(params[:post_id])
    end

    def comment_params
      params.require(:comment).permit(:username, :text)
    end
end

blorgh/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.scoped_to(current_account)
  end

  def show
    #@post = Post.find(params[:id])
    post = Post.scoped_to(current_account).find(params[:id])
  end
end

blorgh/app/helpers/api/comments_helper.rb
module Api::CommentsHelper
end

blorgh/app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

blorgh/app/helpers/application_helper.rb
module ApplicationHelper
end

blorgh/app/helpers/comments_helper.rb
module CommentsHelper
end

blorgh/app/helpers/posts_helper.rb
module PostsHelper
end

blorgh/app/helpers/sessions_helper.rb
module SessionsHelper
end

blorgh/app/views/comments/_comment.html.erb
<div id='comment_<%= comment.id %>' class='comment'>
  <h4><%= comment.id %>.</h4>
  <strong><%= comment.username %></strong>
  <%= simple_format(comment.text) %>
</div>

blorgh/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blorgh</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='row'>
  <div class='col-xs-10 col-md-8 col-md-offset-2 col-xs-offset-1'>
    <div class='row'>
      <div class='pull-right'>
        <%= render 'subscribem/shared/login' %>

      </div>
    </div>
    <div class='row'>
      <% flash.each do |key, text| %>
        <div class='flash flash-<%= key %>'><%= text %></div>
      <% end %>
    </div>
    
    <h1><%= link_to 'My blog', root_path %></h1>
    <p>Read all about it!</p>
    <%= yield %>
  </div>
</div>

</body>
</html>

blorgh/app/views/posts/index.html.erb
<% if admin? %>
  <%= link_to 'New Post', new_admin_post_path, class: 'btn btn-primary' %>
<% end %>

<% @posts.each do |post| %>
  <h2><%= link_to post.title, post %></h2>
  <%= simple_format(post.text) %>
<% end %>

blorgh/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<% if admin? %>
  <%= link_to 'Edit Post', edit_post_path(@post) %> |
  <%= link_to 'Delete Post', post_path(@post), method: :delete %>
<% end %>

<%= simple_format(@post.text) %>

<div class='row'>
  <div class='col-md-6'>
    <h3>Leave a comment</h3>
    <%= form_for [@post, @post.comments.build] do |f| %>
      <p class='form-group'>
        <%= f.label :username %><br>
        <%= f.text_field :username, class: 'form-control' %>
      </p>

      <p class='form-group'>
        <%= f.label :text %><br>
        <%= f.text_area :text, class: 'form-control', rows: 10 %>
      </p>

      <%= f.submit class: 'btn btn-primary' %>
    <% end %>

    <h3>Comments</h3>
    <%= render @post.comments.select(&:persisted?) %>
  </div>
</div>